services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./_pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres